{
  "openapi": "3.0.3",
  "info": {
    "title": "Todolist RESTful API",
    "description": "Documentation Todolist RESTful API and learning OpenAPI",
    "termsOfService": "http.//www.srz.dev.com/terms-of-service",
    "version": "1.0.0",
    "contact": {
      "name": "Shahrizan",
      "email": "shahrizan.learner@gmail.com",
      "url": "https://www.srz-dev.com"
    },
    "license": {
      "name": "Apache 2.0",
      "url": "https://www.apache.org/licenses/LICENSE-2.0.html"
    }
  },
  "externalDocs": {
    "description": "Find more info here",
    "url": "https://www.srz-dev.com/my-api-info"
  },
  "servers": [
    {
      "url": "https://{environment}.srz-dev.com/api/v1",
      "description": "Todolist RESTful API Server",
      "variables": {
        "environment": {
          "default": "dev",
          "enum": ["dev", "qa", "prod"],
          "description": "The target server environment"
        }
      }
    }
  ],
  "tags": [
    {
      "name": "todolist",
      "description": "Operations about todolist"
    }
  ],
  "paths": {
    "/todolist": {
      "get": {
        "tags": [
          "todolist"
        ],
        "summary": "Get all todolist",
        "description": "Only will return active todolist, complete todolist or delted todolist",
        "parameters": [
          {
            "name": "include_done",
            "description": "Include done todolist in the result",
            "required": false,
            "in": "query",
            "schema": {
              "type": "boolean",
              "default": true,
              "nullable": true
            }
          },
          {
            "name": "name",
            "description": "Search todolist by name",
            "required": false,
            "in": "query",
            "schema": {
              "type": "string",
              "nullable": false,
              "minLength": 1,
              "maxLength": 255
            },
            "examples": {
              "java": {
                "description": "Example nama Java",
                "value": "Java"
              },
              "php": {
                "description": "Example nama PHP",
                "value": "PHP"
              }
            }
          }
        ],
        "responses": {
          "200": {
            "description": "Success get all todolist",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/arrayTodoList"
                },
                "examples": {
                  "Success": {
                    "description": "Example data todolist Java",
                    "value": [
                      {
                        "id": 1,
                        "name": "Java",
                        "priority": 1,
                        "tags": ["java", "oop"]
                      },
                      {
                        "id": 2,
                        "name": "PHP",
                        "priority": 2,
                        "tags": ["php", "oop"]
                      }
                    ]
                  }
                }
              }
            }
          }
        },
        "security": [
          {
            "TodolistAuth": []
          }
        ]
      },
      "post": {
        "tags": [
          "todolist"
        ],
        "summary": "Create new todolist",
        "description": "Create new todolist",
        "requestBody": {
          "required": true,
          "content": {
            "application/json": {
              "schema": {
                "$ref": "#/components/schemas/createOrUpdateTodolist"
              },
              "examples": {
                "java": {
                  "description": "Example nama Java",
                  "value": {
                    "name": "Java",
                    "priority": 1,
                    "tags": ["java", "oop"]
                  }
                },
                "php": {
                  "description": "Example nama PHP",
                  "value": {
                    "name": "PHP",
                    "priority": 2,
                    "tags": ["php", "oop"]
                  }
                }
              }
            }
          }
        },
        "responses": {
          "200": {
            "description": "Success create new todolist",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/todolist"
                },
                "examples": {
                  "Java": {
                    "description": "Example data todolist Java",
                    "value": {
                      "id": 1,
                      "name": "Java",
                      "priority": 1,
                      "tags": ["java", "oop"]
                    }
                  },
                  "PHP": {
                    "description": "Example data todolist PHP",
                    "value": {
                      "id": 2,
                      "name": "PHP",
                      "priority": 2,
                      "tags": ["PHP", "oop"]
                    }
                  }
                }
              }
            }
          }
        },
        "security": [
          {
            "TodolistAuth": []
          }
        ]
      }
    },
    "/todolist/{todolistId}": {
      "put": {
        "tags": [
          "todolist"
        ],
        "summary": "Update existing todolist",
        "description": "Update existing todolist in database",
        "parameters": [
          {
            "$ref": "#/components/parameters/todolistId"
          }
        ],
        "requestBody": {
          "required": true,
          "content": {
            "application/json": {
              "schema": {
                "$ref": "#/components/schemas/createOrUpdateTodolist"
              }
            }
          }
        },
        "responses": {
          "200": {
            "description": "Success update existing todolist",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/todolist"
                },
                "examples": {
                  "Java": {
                    "description": "Example data todolist Java",
                    "value": {
                      "id": 1,
                      "name": "Java",
                      "priority": 1,
                      "tags": ["java", "oop"]
                    }
                  },
                  "PHP": {
                    "description": "Example data todolist PHP",
                    "value": {
                      "id": 2,
                      "name": "PHP",
                      "priority": 2,
                      "tags": ["PHP", "oop"]
                    }
                  }
                }
              }
            }
          }
        },
        "security": [
          {
            "TodolistAuth": []
          }
        ]
      },
      "delete": {
        "tags": [
          "todolist"
        ],
        "summary": "Delete existing todolist",
        "description": "Delete existing todolist in database",
        "parameters": [
          {
            "$ref": "#/components/parameters/todolistId"
          }
        ],
        "responses": {
          "200": {
            "description": "Success delete existing todolist",
            "content": {
              "application/json": {
                "schema":{
                  "type": "object",
                  "properties": {
                    "success": {
                      "type": "boolean"
                    }
                  }
                },
                "examples": {
                  "Success": {
                    "description": "Success delete existing todolist",
                    "value": {
                      "success": true
                    }
                  }
                }
              }
            }
          },
          "404": {
            "description": "Todolist not found",
            "content": {
              "application/json": {
                "schema":{
                  "type": "object",
                  "properties": {
                    "success": {
                      "type": "boolean"
                    }
                  }
                },
                "examples": {
                  "Success": {
                    "description": "Todolist not found",
                    "value": {
                      "success": false
                    }
                  }
                }
              }
            }
          }
        },
        "security": [
          {
            "TodolistAuth": []
          }
        ]
      }
    }
  },
  "components": {
    "parameters": {
      "todolistId": {
        "name": "todolistId",
        "description": "The id of todolist to update",
        "required": true,
        "in": "path",
        "schema": {
          "type": "integer",
          "minLength": 1
        },
        "examples": {
          "Java": {
            "description": "Example id Java",
            "value": 1
          },
          "PHP": {
            "description": "Example id PHP",
            "value": 2
          }
        }
      }
    },
    "schemas": {
      "todolist": {
        "type": "object",
        "properties": {
          "id": {
            "type": "integer"
          },
          "name": {
            "type": "string",
            "minLength": 1,
            "required": true
          },
          "priority": {
            "type": "integer",
            "format": "int32",
            "required": true,
            "default": 1
          },
          "tags": {
            "type": "array",
            "required": false,
            "minItems": 1,
            "items": {
              "type": "string",
              "minLength": 1
            }
          }
        }
      },
      "createOrUpdateTodolist": {
        "type": "object",
        "properties": {
          "name": {
            "type": "string",
            "minLength": 1,
            "required": true
          },
          "priority": {
            "type": "integer",
            "format": "int32",
            "required": true,
            "default": 1
          },
          "tags": {
            "type": "array",
            "required": false,
            "minItems": 1,
            "items": {
              "type": "string",
              "minLength": 1
            }
          }
        }
      },
      "arrayTodoList": {
        "type": "array",
        "items": {
          "$ref": "#/components/schemas/todolist"
        }
      }
    },
    "securitySchemes": {
      "TodolistAuth": {
        "type": "apiKey",
        "in": "header",
        "name": "X-API-KEY"
      }
    }
  }
}
